#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- if eq (include "eric-esoa-so-library-chart.global-security-tls-enabled" .) "true" }}
apiVersion: siptls.sec.ericsson.com/v1
kind: InternalCertificate
metadata:
  name: {{ template "eric-esoa-rest-service.name" . }}-server-cert
  labels:
  {{ include "eric-esoa-rest-service.labels" . | nindent 4 }}
  annotations:
  {{ include "eric-esoa-rest-service.annotations" . | nindent 4 }}
spec:
  kubernetes:
    generatedSecretName: {{ .Chart.Name }}-server-cert
    certificateName: tls.crt
    privateKeyName: tls.key
    secretType: tls
  certificate:
    subject:
      cn: {{ .Chart.Name }}
    subjectAlternativeName:
      populateKubernetesDns: true
      dns:
        - localhost # We need localhost in cert for probes
        - certified-scrape-target
    extendedKeyUsage:
      tlsClientAuth: true
      tlsServerAuth: true
  {{- end }}