#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

productName: "Rest Service"
productNumber: "CRX 901 000"
images:
  mainImage:
    productName: "Rest Service"
    productNumber: "CRX 901 000"
    registry: "armdocker.rnd.ericsson.se"
    repoPath: "REPO_PATH"
    name: "eric-esoa-rest-service"
    tag: "IMAGE_TAG"
  pgInitContainer:
    productName: "Document Database PG"
    productNumber: ""
    registry: "armdocker.rnd.ericsson.se"
    repoPath: "proj-esoa-so"
    name: "postgresql13"
    tag: "1.3.2-1"